fouruc/base/urls.py
from django.contrib import admin
from django.urls import path

from fouruc.base import views

app_name = 'base'

urlpatterns = [
    path('', views.dashboard, name='home'),
    path('dashboard', views.dashboard, name='dashboard'),
    path('charts', views.charts, name='charts'),
    path('maps', views.maps, name='maps'),
    path('blank', views.blank, name='blank'),
    path('badges', views.badges, name='badges'),
    path('breadcrumb_pagination', views.breadcrumb_pagination, name='breadcrumb_pagination'),
    path('forms', views.forms, name='forms'),
    path('button', views.button, name='button'),
    path('collapse', views.collapse, name='collapse'),
    path('icons', views.icons, name='icons'),
    path('tabs', views.tabs, name='tabs'),
    path('tables', views.tables, name='tables'),
    path('typography', views.typography, name='typography'),
]

fouruc/manager/urls.py
from django.contrib import admin
from django.urls import path

from fouruc.manager import views

app_name = 'manager'

urlpatterns = [
    #  Gerenciamento de contas
    path('', views.contas, name='contas'),
    path('detalhe/<slug:slug>/', views.conta_detalhe, name='conta_detalhe'),

    #  Atualiza Conta
    path(r'update/<slug:slug>/all', views.update_all_data_account, name='update_data_account'),
    path(r'update/<slug:slug>/players', views.update_players, name='update_players'),
    path(r'update/<slug:slug>/playlists', views.update_playlists, name='update_playlists'),
    path(r'update/<slug:slug>/medias', views.update_medias, name='update_medias'),
    path(r'update/<slug:slug>/categories', views.update_categories, name='update_categories'),

    #  Deleta conta
    path(r'delete/<slug:slug>/', views.delete, name='delete'),

    #  Relatórios
    path('playlogs/', views.playlogs, name='playlogs'),
    path('relatorios/', views.solicitar_relatorio, name='solicitar_relatorio'),

]

fouruc/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('fouruc.authentication.urls')),
    path('', include('fouruc.base.urls')),
    path('contas/', include('fouruc.manager.urls'))

]

fouruc/base/models.py
from django.db import models
from django.utils import timezone
from django.contrib import auth
from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
from django.contrib.auth.models import PermissionsMixin
from django.utils.translation import gettext_lazy as _
from django.core.mail import send_mail
from fouruc.base import apps
from django.contrib.auth.hashers import make_password


class UserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """
        Create and save a user with the given username, email, and password.
        """
        if not email:
            raise ValueError('The given username must be set')
        email = self.normalize_email(email)
        # Lookup the real model class from the global app registry so this
        # manager method can be used in migrations. This is fine because
        # managers are by definition working on the real model.
        # GlobalUserModel = apps.get_model(self.model._meta.app_label, self.model._meta.object_name)
        # username = GlobalUserModel.normalize_username(username)
        user = self.model(email=email, **extra_fields)
        user.password = make_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)

    def with_perm(self, perm, is_active=True, include_superusers=True, backend=None, obj=None):
        if backend is None:
            backends = auth._get_backends(return_tuples=True)
            if len(backends) == 1:
                backend, _ = backends[0]
            else:
                raise ValueError(
                    'You have multiple authentication backends configured and '
                    'therefore must provide the `backend` argument.'
                )
        elif not isinstance(backend, str):
            raise TypeError(
                'backend must be a dotted import path string (got %r).'
                % backend
            )
        else:
            backend = auth.load_backend(backend)
        if hasattr(backend, 'with_perm'):
            return backend.with_perm(
                perm,
                is_active=is_active,
                include_superusers=include_superusers,
                obj=obj,
            )
        return self.none()

class User(AbstractBaseUser, PermissionsMixin):
    """
    Clase usuário para aplicação base.

    E-mail and password are required. Other fields are optional.
    """

    first_name = models.CharField(_('first name'), max_length=150, blank=True)
    email = models.EmailField(_('email address'), unique=True)
    is_staff = models.BooleanField(
        _('staff status'),
        default=False,
        help_text=_('Designates whether the user can log into this admin site.'),
    )
    is_active = models.BooleanField(
        _('active'),
        default=True,
        help_text=_(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        ),
    )
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)

    objects = UserManager()

    EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def clean(self):
        super().clean()
        self.email = self.__class__.objects.normalize_email(self.email)

    def get_full_name(self):
        """
        Return the first_name plus the last_name, with a space in between.
        """
        full_name = '%s' % (self.first_name)
        return full_name.strip()

    def get_short_name(self):
        """Return the short name for the user."""
        return self.first_name

    def email_user(self, subject, message, from_email=None, **kwargs):
        """Send an email to this user."""
        send_mail(subject, message, from_email, [self.email], **kwargs)

fouruc/base/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from decouple import config
from django.views.decorators.cache import cache_page


@cache_page(60 * 10)
@login_required
def dashboard(request):
    return render(request, 'base/index.html')


@login_required
def charts(request):
    return render(request, 'charts-morris.html')


@login_required
def maps(request):
    return render(request, 'maps-google.html')


@login_required
def blank(request):
    return render(request, 'page-blank.html')


@login_required
def badges(request):
    return render(request, 'ui-badges.html')


@login_required
def breadcrumb_pagination(request):
    return render(request, 'ui-breadcrumb-pagination.html')


@login_required
def forms(request):
    return render(request, 'ui-forms.html')


@login_required
def button(request):
    return render(request, 'ui-button.html')


@login_required
def collapse(request):
    return render(request, 'ui-collapse.html')


@login_required
def icons(request):
    return render(request, 'ui-icons.html')


@login_required
def tables(request):
    return render(request, 'ui-tables.html')


@login_required
def tabs(request):
    return render(request, 'ui-tabs.html')


@login_required
def typography(request):
    return render(request, 'ui-typography.html')

fouruc/base/templates/includes/navigation.html
<!-- NOT IMPLEMENTED -->

fouruc/base/templates/includes/scripts.html
{% load static %}
    <!-- Required Js -->
    <script src="{% static 'js/vendor-all.min.js' %}"></script>
    <script src="{% static 'plugins/bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/pcoded.min.js' %}"></script>

fouruc/base/templates/includes/sidebar.html
<nav class="pcoded-navbar">
    <div class="navbar-wrapper">
        <div class="navbar-brand header-logo">
            <a target="" href="{% url 'base:home' %}" class="b-brand">
                <div class="b-bg">
                    <i class="feather icon-trending-up"></i>
                </div>
                <span class="b-title">4UC Manager <up>Lite</up></span>
            </a>
            <a class="mobile-menu" id="mobile-collapse" href="javascript:"><span></span></a>
        </div>
        <div class="navbar-content scroll-div">
            <ul class="nav pcoded-inner-navbar">
                <li data-username="dashboard Default Ecommerce CRM Analytics Crypto Project"
                    class="nav-item {% if 'index' in segment %} active {% endif %}">
                    <a href="{% url 'base:dashboard' %}" class="nav-link "><span class="pcoded-micon"><i
                            class="feather icon-home"></i></span><span class="pcoded-mtext">Dashboard</span></a>
                </li>
                <!--<li class="nav-item pcoded-menu-caption"> <label>Forms & table</label> </li>-->
                <li data-username="form elements advance componant validation masking wizard picker select"
                    class="nav-item {% if 'ui-forms' in segment %} active {% endif %}">
                    <a href="{% url 'base:forms' %}" class="nav-link "><span class="pcoded-micon"><i
                            class="feather icon-file-text"></i></span><span
                            class="pcoded-mtext">Form elements</span></a>
                </li>
                <li data-username="Table bootstrap datatable footable"
                    class="nav-item {% if 'ui-tables' in segment %} active {% endif %}">
                    <a href="{% url 'base:tables' %}" class="nav-link "><span class="pcoded-micon"><i
                            class="feather icon-server"></i></span><span class="pcoded-mtext">Table</span></a>
                </li>
                <!-- <li class="nav-item pcoded-menu-caption"> <label>Chart & Maps</label> </li> -->
                <li data-username="Charts Morris"
                    class="nav-item {% if 'charts-morris' in segment %} active {% endif %}">
                    <a href="{% url 'base:charts' %}" class="nav-link "><span class="pcoded-micon"><i
                            class="feather icon-pie-chart"></i></span><span class="pcoded-mtext">Chart</span></a></li>
                <li data-username="Maps Google"
                    class="nav-item {% if 'maps-google' in segment %} active {% endif %}">
                    <a href="{% url 'base:maps' %}" class="nav-link "><span class="pcoded-micon"><i
                            class="feather icon-map"></i></span><span class="pcoded-mtext">Mapas</span></a></li>
                <!--<li class="nav-item pcoded-menu-caption"> <label>Elementos</label> </li>-->
                <li data-username="basic components Button Alert Badges breadcrumb Paggination progress Tooltip popovers Carousel Cards Collapse Tabs pills Modal Grid System Typography Extra Shadows Embeds"
                    class="nav-item pcoded-hasmenu">
                    <a href="javascript:" class="nav-link "><span class="pcoded-micon"><i class="feather icon-box"></i></span><span
                            class="pcoded-mtext">Components</span></a>
                    <ul class="pcoded-submenu">
                        <li class=""><a href="{% url 'base:button' %}" class="">Button</a></li>
                        <li class=""><a href="{% url 'base:badges' %}" class="">Badges</a></li>
                        <li class=""><a href="{% url 'base:breadcrumb_pagination' %}" class="">Breadcrumb &
                            paggination</a></li>
                        <li class=""><a href="{% url 'base:collapse' %}" class="">Collapse</a></li>
                        <li class=""><a href="{% url 'base:tabs' %}" class="">Tabs & pills</a></li>
                        <li class=""><a href="{% url 'base:typography' %}" class="">Typography</a></li>
                        <li class=""><a href="{% url 'base:icons' %}" class="">Feather<span
                                class="pcoded-badge label label-danger">Novo!</span></a></li>
                    </ul>
                </li>
                <li class="nav-item pcoded-menu-caption">
                    <label>Suporte</label>
                </li>
                 <li data-username="basic components Button Alert Badges breadcrumb Paggination progress Tooltip popovers Carousel Cards Collapse Tabs pills Modal Grid System Typography Extra Shadows Embeds"
                    class="nav-item pcoded-hasmenu">
                    <a href="javascript:" class="nav-link "><span class="pcoded-micon">
                        <i class="feather icon-grid"></i></span><span class="pcoded-mtext">Manager</span></a>
                    <ul class="pcoded-submenu">
                        <li class=""><a href="{% url 'manager:contas' %}" class="">Contas</a></li>
                        <li class=""><a href="{% url 'manager:solicitar_relatorio' %}" class="">Relatórios</a></li>
                    </ul>
                </li>
                <li class="nav-item pcoded-menu-caption">
                    <label>Pages</label>
                </li>
                <!-- <li data-username="Authentication Sign up Sign in reset password Change password Personal information profile settings map form subscribe"
                    class="nav-item pcoded-hasmenu">
                    <a href="javascript:" class="nav-link "><span class="pcoded-micon"><i class="feather icon-lock"></i></span><span
                            class="pcoded-mtext">Authentication</span></a>
                    <ul class="pcoded-submenu">
                        <li class=""><a href="#" class="">Reset Pass</a></li>
                        <li class=""><a href="#" class="">Register (template)</a></li>
                    </ul>
                </li> -->
                <li data-username="Sample Page"
                    class="nav-item {% if 'page-blank' in segment %} active {% endif %}">
                    <a href="{% url 'base:blank' %}" class="nav-link"><span class="pcoded-micon"><i
                            class="feather icon-sidebar"></i></span><span class="pcoded-mtext">Sample page</span></a>
                </li>
                <li data-username="Disabled Menu" class="nav-item">
                    <a href="{% url 'logout' %}" class="nav-link">
                        <span class="pcoded-micon"><i class="feather icon-power"></i></span><span class="pcoded-mtext">Logout</span>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>