fouruc/manager/urls.py
from django.contrib import admin
from django.urls import path

from fouruc.manager import views

app_name = 'manager'

urlpatterns = [
    #  Gerenciamento de contas
    path('', views.contas, name='contas'),
    path('detalhe/<slug:slug>/', views.conta_detalhe, name='conta_detalhe'),

    #  Atualiza Conta
    path(r'update/<slug:slug>/all', views.update_all_data_account, name='update_data_account'),
    path(r'update/<slug:slug>/players', views.update_players, name='update_players'),
    path(r'update/<slug:slug>/playlists', views.update_playlists, name='update_playlists'),
    path(r'update/<slug:slug>/medias', views.update_medias, name='update_medias'),
    path(r'update/<slug:slug>/categories', views.update_categories, name='update_categories'),

    #  Deleta conta
    path(r'delete/<slug:slug>/', views.delete, name='delete'),

    #  Relatórios
    path('playlogs/', views.playlogs, name='playlogs'),
    path('relatorios/', views.solicitar_relatorio, name='solicitar_relatorio'),

]

fouruc/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('fouruc.authentication.urls')),
    path('', include('fouruc.base.urls')),
    path('contas/', include('fouruc.manager.urls'))

]

fouruc/manager/models.py
from django.contrib.postgres.fields import ArrayField
from django.db import models
from django.urls import reverse


class Account(models.Model):
    name = models.CharField(max_length=128, unique=True)
    url = models.CharField(max_length=100, unique=True)
    token = models.CharField(max_length=100)
    slug = models.SlugField(null=True)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.name}"

    def get_absolute_url(self):
        return reverse('manager:conta_detalhe', kwargs={'slug': self.slug})

    class Meta:
        ordering = ['-date_added']


class Playlist(models.Model):
    playlist_id = models.IntegerField()
    name = models.CharField(max_length=128)
    isSubPlaylist = models.BooleanField()
    account = models.ForeignKey(Account, on_delete=models.CASCADE, related_name='playlists')

    def __str__(self):
        return f"{self.playlist_id} - {self.name}"


class Player(models.Model):
    player_id = models.IntegerField()
    name = models.CharField(max_length=128)
    platform = models.CharField(max_length=28)
    lastContactInMinutes = models.IntegerField(null=True)
    group_id = models.IntegerField()
    group_name = models.CharField(max_length=128)
    status_id = models.IntegerField()
    status_name = models.CharField(max_length=128)
    lastLogReceived = models.DateTimeField(null=True)
    playlist = models.ForeignKey(Playlist, on_delete=models.SET_NULL, null=True, related_name='players')
    account = models.ForeignKey(Account, on_delete=models.CASCADE, related_name='players')

    def __str__(self):
        return f"{self.name}"


class Category(models.Model):
    category_id = models.IntegerField()
    name = models.CharField(max_length=64)
    description = models.CharField(max_length=128)
    autoShuffle = models.BooleanField()
    updateflow = models.IntegerField()
    account = models.ForeignKey(Account, on_delete=models.CASCADE, related_name='categories')

    def __str__(self):
        return f"{self.category_id} - {self.name}"


class Client(models.Model):
    name = models.CharField(max_length=128)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.name}"


class Media(models.Model):
    media_id = models.IntegerField()
    name = models.CharField(max_length=128)
    file = models.CharField(max_length=13)
    durationInSeconds = models.IntegerField()
    startDate = models.DateField(blank=True, null=True)
    endDate = models.DateField(blank=True, null=True)
    account = models.ForeignKey(Account, on_delete=models.CASCADE, related_name='medias')
    category = models.ManyToManyField(Category, related_name='medias')
    playlist = models.ManyToManyField(Playlist, related_name='medias')
    client = models.ForeignKey(Client, blank=True, null=True, on_delete=models.SET_NULL, related_name='medias')

    def __str__(self):
        return f"{self.name}"


class Register(models.Model):
    account = models.ForeignKey(Account, on_delete=models.CASCADE, related_name='records')
    nickname = models.CharField(max_length=128)
    date = models.DateField()
    time = models.TimeField()
    player_id = models.IntegerField()
    media_id = models.IntegerField()
    media_type = models.CharField(max_length=2)

    class Meta:
        unique_together = ('date', 'time', 'player_id', 'nickname')
        ordering = ['date', 'time']

    def __str__(self):
        return f"{self.player_id} {self.player_name} {self.date} - {self.time} - {self.media_id}"

fouruc/manager/forms.py
import requests
from django import forms

from fouruc.manager.models import Account
from fouruc.manager.resources.tools import enterprise_or_self


class ContaNovaForm(forms.ModelForm):
    """
   Este formulario va a tratar la entrada de tareas, solamente capturando su nombre.
   """

    class Meta:
        model = Account
        fields = ['url', 'token']

    # this function will be used for the validation
    def clean_url(self):

        # data from the form is fetched using super function
        super(ContaNovaForm, self).clean()

        # extract the url field from the data
        global url
        url = (lambda url: 'https://' + url if 'htt' not in url else url.replace('http', 'https'))(
            self.cleaned_data.get('url'))
        # conditions to be met for the url
        if '4yousee' in url or '4usee' in url:
            # self._errors['url'] = self.error_class(['Minimum 5 characters required'])
            type_account = enterprise_or_self(url)
            if type_account:
                if Account.objects.filter(url=url).exists() or Account.objects.filter(url=url + '/').exists():
                    raise forms.ValidationError("Conta existente.")
                resp = requests.get(url)
                if resp.status_code != 200:
                    raise forms.ValidationError("Não foi possível fazer contato sua conta.")
                else:
                    return url
            else:
                raise forms.ValidationError("Verifique sua URL, pode estar escrita incorretamente.")
        else:
            raise forms.ValidationError("URL inválida.")

        # return any errors if found
        # return self.cleaned_data

    def clean_token(self):
        super(ContaNovaForm, self).clean()

        # extract the url and token field from the data
        token = self.cleaned_data.get('token')

        if not token:
            raise forms.ValidationError("Este Campo é obrigatório.")
        elif len(token) < 30:
            # self._errors['token'] = self.error_class(['Post Should Contain a minimum of 10 characters'])
            raise forms.ValidationError("Token inválido.")
        else:
            resp = requests.request("GET", 'https://api.4yousee.com.br/v1/users', headers={'Secret-Token': token})
            if resp.status_code != 200:
                raise forms.ValidationError("Token inválido.")
            else:
                return token


class RelatorioForm(forms.Form):
    """
   Este formulário vai tratar a solicitação de relatórios.
   """
    try:
        contas = Account.objects.all()
        conta = forms.ChoiceField(choices=list(map(lambda x: (x.slug, x.name), contas)), initial=[("default", "Selecione a Conta")])
    except:
        startdate = forms.DateField()
        enddate = forms.DateField()

fouruc/manager/views.py
import json

from decouple import config
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib import messages
from django.urls import reverse
from django.utils.text import slugify
from django.views.decorators.csrf import csrf_exempt

from fouruc.manager.facade import qty_all_records
from fouruc.manager.forms import ContaNovaForm, RelatorioForm
from fouruc.manager.models import Account
from fouruc.manager.resources.api_handle import DataManager
from fouruc.manager.resources.tools import *
from fouruc.manager.resources.update_bd import *


#  Views para gerenciar as contas

@login_required
def contas(request):
    if request.method == 'POST':
        form = ContaNovaForm(request.POST)
        if form.is_valid():
            account = form.save(commit=False)
            account.name = name_of_account(form.data['url'])
            account.slug = slugify(account.name)
            account.save()
            return HttpResponseRedirect(reverse('manager:contas'))
        else:
            contas = Account.objects.all()
            return render(request, 'manager/contas.html', {'form': form, 'contas': contas}, status=400)
    contas = Account.objects.all()
    return render(request, 'manager/contas.html', {'contas': contas})


@login_required
def conta_detalhe(request, slug):
    conta = get_object_or_404(Account, slug=slug)
    ctx = {'conta': conta, 'total_records': qty_all_records(conta)}
    return render(request, 'manager/conta_detalhe.html', ctx)


def update_all_data_account(request, slug):
    conta = Account.objects.get(slug=slug)
    account = DataManager(conta.token)
    account.get_media_category(), account.get_medias(), account.get_playlists(), account.get_players()
    msg_errors = ''
    msg_sucess = []
    if not account.media_category:
        msg_errors += "• Não foi possível capturar informações das categorias."
    else:
        if categories_entered := update_or_insert_categories(conta, account.media_category):
            msg_sucess.append(f'{categories_entered} Categorias')

    if not account.medias:
        msg_errors += "\n• Não foi possível capturar informações dos conteúdos."
    else:
        if medias_entered := update_or_insert_medias(conta, account.medias):
            msg_sucess.append(f'{medias_entered} Medias')

    if not account.playlists:
        msg_errors += "\n• Não foi possível capturar informações das playlists e por causa disso não podem ser obtidos os dados dos players."
    elif not account.players:
        if playlists_entered := update_or_insert_playlists(conta, account.playlists):
            msg_sucess.append(f'{playlists_entered} Playlists')
        msg_errors += "\n• Não foi possível capturar informações dos players."
    else:
        if playlists_entered := update_or_insert_playlists(conta, account.playlists):
            msg_sucess.append(f'{playlists_entered} Playlists')
        if players_entered := update_or_insert_players(conta, account.players):
            msg_sucess.append(f'{players_entered} Players')

    messages.success(request, f"{', '.join(msg_sucess)} obtidos com sucesso !")
    messages.error(request, msg_errors)
    # By passing some object to redirect(); that object’s get_absolute_url() method will be called to figure out the redirect URL
    return redirect(conta)


def update_players(request, slug):
    conta = Account.objects.get(slug=slug)
    account = DataManager(conta.token)
    account.get_players()
    if not account.players:
        messages.error(request, "Não foi possível capturar informações dos players.")
        return redirect(conta)
    else:
        if records := update_or_insert_players(conta, account.players):
            messages.success(request, f'{records} Players obtidos!')
            return redirect(conta)
        else:
            messages.error(request, "Não foi possível capturar informações dos players.")
            return redirect(conta)


def update_categories(request, slug):
    conta = Account.objects.get(slug=slug)
    account = DataManager(conta.token)
    account.get_media_category()
    if not account.media_category:
        messages.error(request, "Não foi possível capturar informações das categorias")
        return redirect(conta)
    else:
        if categories_entered := update_or_insert_categories(conta, account.media_category):
            messages.success(request, f'{categories_entered} Categorias obtidas!')
            return redirect(conta)


def update_playlists(request, slug):
    conta = Account.objects.get(slug=slug)
    account = DataManager(conta.token)
    account.get_playlists()
    if not account.playlists:
        messages.error(request, "Não foi possível capturar informações das playlists")
        return redirect(conta)
    else:
        if playlists_entered := update_or_insert_playlists(conta, account.playlists):
            messages.success(request, f'{playlists_entered} Playlists obtidas!')
            return redirect(conta)


def update_medias(request, slug):
    conta = Account.objects.get(slug=slug)
    account = DataManager(conta.token)
    account.get_medias()
    if not account.medias:
        messages.error(request, "Não foi possível capturar informações dos conteúdos")
        return redirect(conta)
    else:
        if medias_entered := update_or_insert_medias(conta, account.medias):
            messages.success(request, f'{medias_entered} Medias obtidas!')
            return redirect(conta)


def delete(request, slug):
    conta = Account.objects.get(slug=slug)
    conta.delete()
    return HttpResponseRedirect(reverse('manager:contas'))


#  Views para relatório

@csrf_exempt
def playlogs(request):
    """
    Essa view corresponde a url path informada como webhook para receber os relatórios solicitados vía api do 4yousee manager.
    :param request:
    :return: Não retorna informações úteis pois o objetivo é so receber requesições post.
    """
    if request.method == 'POST':
        content = bytes_to_dict(request.body)
        data_response = json.dumps(content, indent=2)
        print(content)
        file = download_gz(content['url'])
        if data := process_file(file):
            #  Se o relatório recebido possui playlogs
            name_account = name_of_account(content['url'])
            try:
                conta = Account.objects.get(name__contains=name_account.split('-')[0].capitalize())
                records = insert_records(conta, data)
            except Exception as e:
                print('Error: ', e)
            return HttpResponse(f"<h4>{records} playlogs inseridos com sucesso!'</h4>")
        else:
            return HttpResponse(f"<h6 class='lead'>Não houve resultados no relatório solicitado da conta {name_of_account(content['url']).capitalize()}</h6>")
    return HttpResponse("<h4 class='lead'>Site usado como webhook para receber respostas da API do 4YouSee Manager</h4>")


@login_required
@csrf_exempt
def solicitar_relatorio(request):
    if request.method == 'POST':
        form = RelatorioForm(request.POST)
        if form.is_valid():
            slug_conta = (form.cleaned_data['conta'])
            startdate = str(form.cleaned_data['startdate'])
            enddate = str(form.cleaned_data['enddate'])
            conta = Account.objects.get(slug=slug_conta)
            account = DataManager(conta.token)
            params = dict(type='detailed', webhook=request.build_absolute_uri(reverse('manager:playlogs')),
                          filter={'startDate': startdate, 'endDate': enddate,
                                  'startTime': '00:00:00', 'endTime': '23:59:59',
                                  'mediaId': [], 'playerId': [], 'sort': -1})
            if params['webhook'].startswith('http://127.0.0.1'):
                messages.error(request, 'Não é possível solicitar o relatório com o ambiente local configurado')
                return HttpResponseRedirect(reverse('manager:solicitar_relatorio'))
            elif (resp_post := account.post_report(params)):
                    if resp_post.status_code != 200:
                        resp = json.loads(resp_post.text)
                        messages.error(request, resp['details']['report'][0])
                        return HttpResponseRedirect(reverse('manager:solicitar_relatorio'))
                    else:
                        messages.success(request, f"Relatório solicitado com sucesso. <a href={conta.get_absolute_url()}#playlogs>Ver Playlogs</a>")
                        return HttpResponseRedirect(reverse('manager:solicitar_relatorio'))
        else:
            ctx = {'contas': Account.objects.all(), 'form': form}
            return render(request, 'manager/solicitar_relatorio.html', ctx, status=400)


    else:
        form = RelatorioForm()
        ctx = {'contas': Account.objects.all(), 'form': form}
        return render(request, 'manager/solicitar_relatorio.html', ctx)

fouruc/manager/templates/manager/contas.html
{% extends "layouts/base.html" %}

{% load filter_extras %}

{% block title %} Contas {% endblock %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

<div class="pcoded-content">
    <div class="pcoded-inner-content">
        <!-- [ breadcrumb ] start -->
        <div class="page-header">
            <div class="page-block">
                <div class="row align-items-center">
                    <div class="col-md-12">
                        <div class="page-header-title">
                            <h5 class="m-b-10">Contas</h5>
                        </div>
                        <ul class="breadcrumb">
                            <li class="breadcrumb-item"><a href="/"><i class="feather icon-home"></i></a></li>
                            <li class="breadcrumb-item"><a href="/contas">Adicionar Contas</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <!-- [ breadcrumb ] end -->
        <div class="main-body">
            <div class="page-wrapper">
                <!-- [ Main Content ] start -->
                <div class="row">
                    <div class="col-sm-12">
                        {% include 'messages.html' %}
                        <div class="card">
                            <div class="card-header">
                                <h5>Adicionar Conta</h5>
                            </div>
                            <div class="card-body">
                                <form action="{% url 'manager:contas' %}" method="post">
                                    {% csrf_token %}
                                    <div class="row g-3 align-items-top">
                                        <div class="col-sm-5">
                                            <div>
                                                <input name="url" type="text" class="form-control"
                                                       placeholder="URL da Conta" aria-label="URL da Conta">
                                            </div>
                                            <small class="form-text text-muted">{{ form.errors.url }}</small>
                                        </div>
                                        <div class="col-sm-5">
                                            <div>
                                                <input name="token" type="text" class="form-control" placeholder="Token"
                                                       aria-label="Token">
                                            </div>
                                            <small class="form-text text-muted">{{ form.errors.token }}</small>
                                        </div>
                                        <div class="col-auto">
                                            <button type="submit" class="btn btn-primary">Adicionar</button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div><!-- [ Adicionar Card Content ] end -->

                        {% if contas %}
                        <div class="col-sm-12">
                            <h5 class="mb-3">Contas</h5>
                            <hr>
                        </div>
                        <div class="row">
                            {% for conta in contas %}
                                <div class="col-md-6 col-lg-4">
                                    <div class="card">
                                        <div class="card-header">
                                            <h5><a href="{{ conta.get_absolute_url }}">{{ conta }}</a></h5>
                                            <span class="d-block pt-2"><a
                                                    href="{{ conta.url }}" target="_blank">{{ conta.url }}</a></span>
                                            <div class="card-header-right">
                                                <div class="btn-group card-option">
                                                    <button type="button" class="btn dropdown-toggle"
                                                            data-toggle="dropdown"
                                                            aria-haspopup="true" aria-expanded="false">
                                                        <i class="feather icon-more-horizontal"></i>
                                                    </button>
                                                    <ul class="list-unstyled card-option dropdown-menu dropdown-menu-right"
                                                        x-placement="bottom-end"
                                                        style="position: absolute; will-change: transform; top: 0px; left: 0px; transform: translate3d(54px, 41px, 0px);">

                                                        <li class="dropdown-item full-card"><a href="#!">
                                                            <span><i class="feather icon-maximize"></i> maximizar</span>
                                                            <span style="display:none"><i
                                                                    class="feather icon-minimize"></i> Restaurar</span></a>
                                                        </li>
                                                        <li class="dropdown-item minimize-card"><a href="#!">
                                                            <span><i class="feather icon-minus"></i> colapsar</span>
                                                            <span style="display:none"><i class="feather icon-plus"></i> expandir</span></a>
                                                        </li>
                                                        <li class="dropdown-item">
                                                            <a href="{{ conta.get_absolute_url }}"><i class="feather icon-file-text"></i> Ver Mais</a>
                                                        </li>
                                                        <li class="dropdown-item close-card">
                                                            <a href="{% url 'manager:delete' conta.slug %}">
                                                                <i class="feather icon-trash"></i><span class="text-danger">eliminar</span></a>
                                                        </li>

                                                    </ul>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="card-body">
                                            {% if conta|all_records %}
                                            <div>
                                                <p class="card-text mb-0">Playlogs: {{ conta.records.all|length }}</p>
                                                <p class="card-text mb-0">Players: {{ conta.players.all|length }}</p>
                                                <p class="card-text mb-0">Playlists: {{ conta.playlists.all|length }}</p>
                                                <p class="card-text mb-0">Conteúdos: {{ conta.medias.all|length }}</p>
                                                <p class="card-text">Categorias: {{ conta.categories.all|length }}</p>
                                            </div>
                                            {% else %}
                                            <div class="mt-2 mb-4 text-center">
                                                <p class="lead">Sem Informações</p>
                                            </div>
                                            {% endif %}
                                        </div>
                                    </div>
                                </div>
                            {% empty %}
                            {% endfor %}
                        </div>
                        {% else %}
                        <div class="mt-5 text-center">
                            <h3 class="display-5 text-muted">Não há contas registradas</h3>
                        </div>
                        {% endif %}

                    </div>
                </div>
                <!-- [ Main Content ] end -->
            </div>
        </div>
    </div>
</div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

fouruc/manager/templates/manager/solicitar_relatorio.html
{% extends "layouts/base.html" %}

{% load filter_extras %}

{% block title %} Contas {% endblock %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}
<div class="pcoded-content">
    <div class="pcoded-inner-content">
        <!-- [ breadcrumb ] start -->
        <div class="page-header">
            <div class="page-block">
                <div class="row align-items-center">
                    <div class="col-md-12">
                        <div class="page-header-title">
                            <h5 class="m-b-10">Relatórios</h5>
                        </div>
                        <ul class="breadcrumb">
                            <li class="breadcrumb-item"><a href="/"><i class="feather icon-home"></i></a></li>
                            <li class="breadcrumb-item"><a href="/contas">Solicitar Relatórios</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <!-- [ breadcrumb ] end -->
        <div class="main-body">
            <div class="page-wrapper">
                <!-- [ Main Content ] start -->
                <div class="row">
                    <div class="col-sm-12">
                        {% include 'messages.html' %}
                        <div class="card">
                            <div class="card-header">
                                <h5>Solicitar Relatórios</h5>
                            </div>
                            <div class="card-body">
                                <form action="{% url 'manager:solicitar_relatorio' %}" method="post">
                                    {% csrf_token %}
                                    <div class="form-inline row g-3 align-items-top">
                                        <div class="form-group mx-sm-4">
                                            <label for="inputConta" class="sr-only">Conta</label>
                                            <select class="form-control" name="{{ form.conta.name }}" id="{{ form.conta.id }}">
                                                <option selected>Selecionar conta</option>
                                                {% for conta in contas.all %}
                                                <option value="{{ conta.name|lower }}">{{ conta.name|title }}</option>
                                                {% endfor %}
                                            </select>
                                        </div>
                                        <div class="form-group mx-sm-3">
                                            <label for="inputStartdate" class="sr-only">startDate</label>
                                            <h5 class="mr-2 lead">Desde</h5>
                                            <input type="date" name="{{ form.startdate.name }}" class="form-control">
                                        </div>
                                        <div class="form-group mx-sm-3">
                                            <label for="inputendDate" class="sr-only">endDate</label>
                                            <h5 class="mr-2 lead">Até</h5>
                                            <input type="date" name="{{ form.enddate.name }}" class="form-control">
                                        </div>
                                        <button type="submit" class="btn btn-primary">Solicitar</button>
                                    </div>
                                    <div class="d-flex justify-content-around">
                                        <small class="form-text text-muted w-25 text-danger">{{ form.errors.conta.as_text }}</small>
                                        <small class="form-text text-muted w-25 text-danger">{{ form.errors.startdate.as_text }}</small>
                                        <small class="form-text text-muted w-25 text-danger">{{ form.errors.enddate.as_text }}</small>
                                        <small class="form-text text-muted"></small>
                                    </div>
                                </form>
                            </div>
                        </div><!-- [ Adicionar Card Content ] end -->
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}